### ISSUE TITLE
binder and ashmem not found

### ISSUE THREAD

**Issue by RudraSwat** [WayDroid/anbox-halium#11]
I ran the install script on focal (on a desktop, not a phone) and running the `run-container.sh` script resulted in an error saying that `binder` and `ashmem` were not found, despite being present in the Ubuntu kernel config (verified with modprobe and modinfo). Removing the kernel module check resulted in a number of errors about not being able to mount non-existent block devices.

**Comment by Techwizz-somboo** [comment]
Yeah same problem here.

**Comment by afalout** [comment]
Same here - @RudraSwat  - Why was this closed without any resolution?
